netorkpushdelay=10
httpskeyfile=conf/192.168.199.120.key
enableerrorsshow=true
iec104calldelaytime=900
staticcachefilesize=52428800
isdebug=false
mysqluser=root
graceful=false
tokenexpirestime=720
sessionname=ISMSession
gzipcompresslevel=1
staticextensionstogzip=.css, .js, .png, .jpg, .ico, .mp4, .lic, .ttf,
servername=ISM
modbusserverport=6000
customdatadealwithdelaytime=1000
realdatasyncdelay=100
checkmachinecodetype=1
mysqlport=3307
httpsport=5622
postgrespwd=000000
realdatachanelcache=20000
wsport=10225
sessionon=true
copyrequestbody=true
maxmemory=209715200
sessionsookielifetime=36000
staticdatadealwithdelaytime=1000
mysqlhost=127.0.0.1
httpport=8081
enablemqttbreoken=true
sessionproviderconfig=./data/sessionon
enablehttptls=true
recordpath=D:\record\
postgresuser=postgres
postgresdbname=ism
mysqldbname=ism
directoryindex=false
recoverpanic=true
sessiongcmaxlifetime=36000
includedmethods=get;post
mysqlpwd=ism2024!
jwtkey=4ti7ng2y0u
wsaddress=
runmode=prod
enablehttp=true
gzipminlength=10
postgreshost=127.0.0.1
sessionprovider=file
enablegzip=true
dbtype=4
appname=ISM
postgresport=5432
autoopenurl=false
oceanbaseuser=root@ism_tenant
oceanbasepwd=ism2024!
oceanbasehost=127.0.0.1
oceanbaseport=2881
oceanbasedbname=ism
casauthurl=
httpscertfile=conf/192.168.199.120.crt
enablehttps=true
clearalarmtype=0
history_keep_days=7

