historyrecorddbtype=2
oncewritehistorycounts=100
partitiontype=0

[pg]
host=127.0.0.1
port=5432
user=postgres
password=000000
dbname=ism

[tdengine]
tdenginehost=127.0.0.1
username=root
password=taosdata
tdengineport=6041

[chickhouse]
chickhouseport=9000
chickhousehost=192.168.50.129
username=default
password=000000
database=ISM
connecttimeout=30s
readtimeout=60s

[influxdb]
bucket=historydb
url=http://127.0.0.1:8086
token=J0VBbaLEGr3VysNRiJWVwewjWQdLHHRCP0tkMNnpUmCH50_L_IN0AXi-YEPUCzuawbmCLVPr5k8bWQ18E8dFZw==
org=ism

