isenable=true
mqttcloudplat=1

[mqtt]
subscribetopic=/sys/${ClientID}/post
clientid=ismtest
publishtopic=/sys/${ClientID}/pub
username=czy
password=Czy20140904
brokerhost=127.0.0.1
tls=false
certpath=
brokerport=18883
[EmqxWeb]
Host=127.0.0.1
Port=18083
APIKey=23a808a53adc53eb
SecretKey=ODjOMy2SidBDYbwj2hVSZd5yFQksNQjEwS7LZYUPeXD


