opcua_publish_product_name=ISM OPC UA Publisher2034
opcua_publish_manufacturer_name=ISM
opcua_publish_security_policy_none=true
opcua_publish_enable=true
opcua_publish_allow_anonymous=false
opcua_publish_allow_username=true
opcua_publish_message_security_modes=Sign,SignAndEncrypt,None
opcua_publish_insecure_skip_verify=true
opcua_publish_security_policies=Aes128Sha256RsaOaep,None
opcua_publish_cert=conf/192.168.199.120.crt
opcua_publish_server_name=ismopcuaeee
opcua_publish_server_diagnostics=true
opcua_publish_password=ism123456
opcua_publish_require_external_cert=false
opcua_publish_key=conf/192.168.199.120.key
opcua_publish_port=4841
opcua_publish_host=127.0.0.1
opcua_publish_product_uri=https://www.ismctl.com
opcua_publish_username=ismopcua

